### ISSUE TITLE
Entity_alternative `active` interpretation

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Database-API#316] opened 2023-11-21 10:52 UTC
When getting entities from DB, it's not clear whether to pick all entities unless they have `active` set to false or to pick only entities that have `active` set to true.

v0.7 works this way:
- 0-d entity_classes with is_active tool/feature: pick only the ones that are is_active. Influenced by 'default' value.
- 0-d entity_classes without is_active tool/feature: pick all
- n-d entity_classes without is_active tool/feature: pick only those that are dependents of 0-d entity classes
- n-d entity classes with is_active --> I haven't tested

v0.8 should work in similar way:
- 0-d entity classes: a DB choice for the entity_class whether to be 'include by default' or 'exclude by default'. The default is 'exclude by default'. *
- n-d entity classes: include all dependents by default. Individual entities can then be excluded using `active` = false. An option to switch to 'exclude by default' for the entity_class.  (So opposite default assumption compared to 0-d). 

* Unless we want to fully replicate v0.7 --> then we would need to check first if there are any entity_alternative definitions for the class, and if there are, then start excluding by default - and otherwise include by default. Naturally then, if the user chooses either, that would override this interpretation thingy. Sounds too complicated in my view. A 0.8 DB can be made to work like 0.7 by setting the class options correctly and that should be enough.

**Comment by manuelma** [comment] 2023-11-21 16:28
You're missing the default_value aspect in v0.7 I believe: v0.7 looks at the default_value field from parameter_definition if the value field for parameter_value is null. In SpineOpt at least, the default_value for all is_active parameters is True, which means an entity will pass the tool filter *unless* is_active is set to False individually for it. This is exactly the behavior in v0.8: an entity passes the filter unless there it's entity_alternative has active=False (for the winning alternative).

So behavior in 0.7 is DB dependant (perhaps in your case the default_value of is_active is False?)
Anyways I agree we need to make it more clear.

**Comment by jkiviluo** [comment] 2023-11-21 18:35
Right. I hadn't even realised that.

Anyway, looks like entity_class should have one more column for `include by default`, that would be *false* for new 0-d entity_classes and *true* for new n-d entity_classes. And for existing SpineOpt DBs we would make it *true* for 0-d entity classes as well. 

Then it's debatable what should be the defaults in SpineOpt template DB. My gut feeling would be to make unit, node and connection false, but all others true. But that should be discussed in SpineOpt.

**Comment by manuelma** [comment] 2023-11-22 07:33
Sounds good @jkiviluo 

Maybe I'm getting it wrong, but it looks like you're proposing a different treatment depending on whether the entity is zero-d or multi-d? I don't think that would be a very good idea. Multi-d entities are no different thatn zero-d entities in the sense they can be active or inactive in any alternative. If any entity is inactive, then it is excluded by the filter as well as any stuff in the DB that depends on it - for instance, multi-d entities where the filtered entity is one of the elements.

**Comment by jkiviluo** [comment] 2023-11-22 08:06
I'm just proposing a different default behaviour (you can do either by changing the setting). 

The reason for divergence is that N-d entities are dependents - it's rare that you want to exclude them if you have the elements in. However, when building a model, I prefer to be explicit which 0-D entities I'm taking in. This way, when building scenarios, I can build the scenarios up like building legos. If it's the other way, I have a full lego building and then I start taking parts away, which is less intuitive for me. But this seems to be a matter of taste.

**Comment by jkiviluo** [comment] 2023-11-24 09:47
Updated the issue description and it should be up-to-date with the current plan forward.

**Comment by manuelma** [comment] 2024-02-01 09:50
Nice work @soininen !
However I think the migration script needs to set active_by_default depending on the default_value of the is_active parameter_definition rather than just applying the default rule (false for 0-D, true for (n>0)-D).

Otherwise plenty of SpineDBs will be broken by the migration script!

Still, I feel the "rule" is a bit arbitrary and difficult to remember. I would prefer if everything had active_by_default equal to true. The current rule might result in errors that are very difficult to diagnose. Anyways, I will fix the script for now...

**Comment by soininen** [comment] 2024-02-01 10:00
> However I think the migration script needs to set active_by_default depending on the default_value of the is_active parameter_definition rather than just applying the default rule (false for 0-D, true for (n>0)-D).

That is intentional. The description says (emphasis mine):

> Unless we want to fully replicate v0.7 --> then we would need to check first if there are any entity_alternative definitions for the class, and if there are, then start excluding by default - and otherwise include by default. Naturally then, if the user chooses either, that would override this interpretation thingy. **Sounds too complicated in my view.** A 0.8 DB can be made to work like 0.7 by setting the class options correctly and that should be enough.

If I got this right, the plan was all along to not migrate the default setting but let users fix the database manually afterwards.

In any case, I have no strong feelings about this or whether the default value is true or false. If we come to a conclusion that things need to change, that is OK for me.

**Comment by manuelma** [comment] 2024-02-01 10:15
Ah, I see, thank you @soininen - I miss that part in the description. Although the description talks about maybe looking at entity_alternative to figure out what the active_by_default should be - I am saying something different, that we should look at the default_value of the is_active parameter definition. That is simple and at least helps migrating SpineOpt DBs without painful manual intervention from the user. We can't ask the user something like that I don't think.

I think our SpineOpt users would be very disappointed and we need to protect them, even if they are not too many.

**Comment by soininen** [comment] 2024-02-01 10:34
> I am saying something different, that we should look at the default_value of the is_active parameter definition.

Alright, now I get what you are after! Sorry for my thickheadedness.

There is a small problem (not even sure if it is a problem): the migrations where we switch from is_active to entity alternative and where we introduce active_by_default are separate which means that when it comes time to migrate to active_by_default, the tool/feature/method information has been lost. I guess we do not delete the is_active parameter so we could rely on that still. Would that be OK?

**Comment by jkiviluo** [comment] 2024-02-01 10:41
Sorry for not thinking about the default value - we were not using that. Sounds good if it's considered when it's available.

**Comment by manuelma** [comment] 2024-02-01 11:19
No worries @jkiviluo - I also missed that and just found out now when I was trying to run an old workflow. @soininen I believe we are fine, the previous migrations didn't dropped the tool, feature, and method tables. We also haven't deleted the is_active parameter_definitions. We thought we might need all that in the future and I guess we were right.

**Comment by soininen** [comment] 2024-02-01 11:45
>  the previous migrations didn't drop the tool, feature, and method tables.

This is good news! I'll get the active_by_default migration fixed, then.

**Comment by manuelma** [comment] 2024-02-01 11:59
Ah ok cool! Maybe you can look at the other migration script where we migrate is_active, maybe there is some stuff we can reuse...

**Comment by soininen** [comment] 2024-02-01 12:08
The compatibility transformation seems to be a bit broken - see spine-tools/Spine-Toolbox#2535. Good opportunity to get that one fixed as well.

**Comment by DillonJ** [comment] 2024-02-05 09:50
I missed this discussion originally - it's obviously a critical one and we use is_active extensively in our workflows and SpineOpt datastores.

I don't see a reason here for changing the behaviour in 0.8 unless there is a very compelling reason to do so. The new implementation needs to be fully backwards compatible with 0.7 - otherwise the complexity of migrating existing DBs and workflows to 0.8 is excessive and risky. For SpineOpt I don't believe the behaviour should change depending on entity types or by entity class - this level of complexity/inconsistency will make it overly difficult to migrate existing workflows and SpineOpt data stores and will lead to unexpected behaviour that won't easily be detected. Workflows will appear to work and the subtleties of these changes might be very difficult to untangle.

**Comment by DillonJ** [comment] 2024-02-05 09:55
I think this issue is a good example of the dangers of changing the default behaviour - it could be very problematic.

https://github.com/spine-tools/Spine-Toolbox/issues/2504

**Comment by manuelma** [comment] 2024-02-05 10:02
Thank you @DillonJ - just to clarify, @soininen has fixed the migration script to look at the default_value of is_active which means SpineOpt DBs will be migrated correctly - they will be ready to execute without manual intervention because active_by_default will be true everywhere.

That said, the issue still persists, that some users might not understand the rationale behind our 'rule' and be confused and lost as @Tasqu was.

Our rule might be nice and understandable and all that, but I think the *vast* majority of users would expect 'active_by_default' to not depend on the dimensionality of the class, and have a flat value of true.

**Comment by jkiviluo** [comment] 2024-02-05 12:47
I have to demur. n-dimensional is different from 0-dimensional, because n-dimensional entities have parents. If the parents are in the model, it typically makes sense that the childs will be there too. E.g. 'coal__coal_plant' should automatically be included when both 'coal' and 'coal_plant' are in the model. So, assuming True makes sense for n-dimensional. 

0-dimensional is another matter, because it depends on your model building philosophy: are you adding things or deducting things. If one assumes that everything in the database will be automatically part of the model, that's one approach. Another approach is to pick the parts you want, using alternatives, to form the model in a given scenario. To me, the latter is more sensible approach.

Please remember that this choice affects only new 0-d entity classes created by the user - DBs created from a template will inherit the choices made by the DB developer (and DBs migrated from 0.7 will inherit the style they have used based on is_active parameters).

In case of @tasqu, there are further things going on - his DB was migrated before the update and there is something funny with Base (see his latest comment).

**Comment by manuelma** [comment] 2024-02-05 13:33
> In case of @Tasqu, there are further things going on - his DB was migrated before the update and there is something funny with Base (see his latest comment).

Yeah, I need to look into that. But none of that changes the fact that he at least was expecting entities to pass the filter. I bet the vast majority of users will expect that too.The use case where all the entities are there and you need to select which ones you want is the only one for which active_by_default=false makes sense.

But think about it this way. I am a new user, I create an entity class without paying attention to active_by_default (didn't read the docs, not sure whay it means, whatever). Then add some entities, try to use the database in my application, and see that none of the entities seem to be there. We can show a nice error message, but users don't read error messages. They go directly to the issue tracker and open an issue. We will be bombarded by issues "my entities are not there". It puts a barrier on the simplest use case and we should stay away of it. That's my opinion. I suggest we ask other people, especially users.

**Comment by DillonJ** [comment] 2024-02-22 14:35
Dp we still think it's wise to have behaviour that changes depending on the dimensionality of the class? I think we're asking for trouble and verging on user-hostile. Another issue on it: https://github.com/spine-tools/Spine-Toolbox/issues/2611

**Comment by soininen** [comment] 2024-05-16 12:12
All entities are now active by default so I think we can close this.

**Closed by soininen** 2024-05-16 12:12 UTC
Labels: core
